### ISSUE TITLE
is it working in synergy / with Vue Loader and Nuxt?

### ISSUE THREAD

**Issue by valeriosillari** [itgalaxy/webpack-modernizr-loader#99]
I'm working with VueJS (specifically with NuxtJS) and I got an issue to use this loader.

In particular I'm trying to load the loader as extend loader for Nuxt in the nuxt.config.js file.
Nuxt has its own way to add loaders to webpack (for what I understand).

Questions:

1) Is the loader working with Vue and Vue Loader?

2) Is the loader working with Nuxt?
If so could you provide some snippets/example for adding it?

Best

**Comment by alexander-akait** [comment]
Please provide reproducible test repo, i don't know, but should be work

**Comment by valeriosillari** [comment]
yep you're right.

I've created a test repo here:
https://github.com/valeriosillari/-nuxt-modernizr

In the Readme file you could find the info about the files where I guess the code should be set.

Any suggestions and help is welcome :)

**Comment by gaisinskii** [comment]
@valeriosillari  My solution that works for me:

1) Create a `modernizrrc.js` file with your modernizr options.

```
module.exports = {
  minify: true,
  options: ['addTest', 'setClasses'],
  'feature-detects': []
}
```
2) Create a `modernizr.client.ts` file in your NuxtJS plugins folder (note that i am using typescript, you can ditch ts part

```
import Vue from 'vue'
import MobileDetect from 'mobile-detect'
const Modernizr = require('modernizr')

declare module 'vue/types/vue' {
  interface Vue {
    $isMobile: boolean
    $isPhone: boolean
    $isTablet: boolean
    $isBot: boolean
  }
}

(function initModernizr (Modernizr) {
  const md = new MobileDetect(
    navigator.userAgent
  )
  const grade = md.mobileGrade()
  Modernizr.addTest({
    mobile: !!md.mobile(),
    phone: !!md.phone(),
    tablet: !!md.tablet(),
    bot: !!md.match(
      'googlebot|bingbot|yandex|baiduspider|facebookexternalhit|twitterbot|rogerbot|linkedinbot|embedly|quora|showyoubot|outbrain|pinterestbot|slackbot|vkShare|W3C_Validator'
    ),
    mobilegradea: grade === 'A'
  })
})(Modernizr)

Vue.prototype.$isMobile = Modernizr.mobile
Vue.prototype.$isPhone = Modernizr.phone
Vue.prototype.$isTablet = Modernizr.tablet
Vue.prototype.$isBot = Modernizr.bot
```

3) In your `nuxt.config.js` extend the build property **and be sure to pass correct path to your modernizrrc.js !!!**

```
  build: {
    extend (config, { isClient }) {
      if (isClient) {
        config.module.rules.push({
          test: /modernizrrc\.js$/,
          use: { loader: 'webpack-modernizr-loader' }
        })
        config.resolve.alias.modernizr$ = path.resolve(
          __dirname,
          '../../modernizrrc.js'
        )
      }
    }
  },
```
4) Add your plugin to `nuxt.config.js` plugins property

```
plugins: ['@/plugins/modernizr.client.ts'],
```

**Comment by alexander-akait** [comment]
PR welcome to docs

**Comment by 7iomka** [comment]
Someone knows how to do same thing as @andynoir but in Next.js? Thanks!

**Comment by valeriosillari** [comment]
Found a nuxt plugin helping me with this issue:

https://github.com/dword-design/nuxt-modernizr#readme
